Update release builder for UI

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -3,19 +3,30 @@ name: Build Release
 on:
   push:
     branches:
-      - '*.build'
+      - '**\.build/*'
       - 'release/*'
+      - '!**\.gen'
 
 jobs:
   autocommit:
     name: Build Release
     runs-on: ubuntu-latest
     container:
-      image: atk4/image:latest
+      image: atk4/image:latest-npm
     steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.ref }}
+
+      - name: Target variables - discover
+        id: target
+        run: |
+          echo "::set-output name=version_name::$(echo '${{ github.ref }}' | sed -E 's~.+/~~')"
+
+      - name: Target variables - show
+        run: |
+          echo "Target Version: ${{ steps.target.outputs.version_name }}"
+          if ! echo "${{ steps.target.outputs.version_name }}" | grep '^[0-9]\+\.[0-9]\+\.[0-9]\+'; then echo "ERROR: Version must have [0-9].[0-9].[0-9] format!"; exit 1 ; fi
 
       - name: Install PHP dependencies
         run: composer update --ansi --prefer-dist --no-interaction --no-progress --optimize-autoloader
@@ -41,52 +52,28 @@ jobs:
       - name: Composer validate config
         run: composer validate --strict --no-check-lock && composer normalize --dry-run --no-check-lock
 
-
-# TODO
-      - uses: actions/checkout@master
-      - name: Update CDN destination
-        shell: bash
+      - name: Update version in src/App.php
         run: |
-          v=$(echo ${{ github.ref }} | cut -d / -f 4)
-          echo "::set-env name=version::$v"
+          sed -i "s|public \$version.*|public \$version = '${{ steps.target.outputs.version_name }}';|" src/App.php
 
-          git branch
-          #sed -i "s|'https://raw.githack.com/atk4/ui/develop/public.*|'https://cdn.jsdelivr.net/gh/atk4/ui@$v/public',|" src/App.php
-          # it was develop, it can stay develop for DEVELOP branch, so we see changes to JS right away.
-
-          # Set next version for develop branch
-          a=( ${v//./ } )
-          nv=${a[0]}"."$(( ${a[1]} +1 ))".0-BETA"
-          sed -i "s|public \$version.*|public \$version = '$nv';|" src/App.php
-          git config --global user.email "bundler@agiletoolkit.org"
-          git config --global user.name "Release Bundler"
-          git commit -am "Update versions for develop"
-
-# TODO
-
-      - name: Compile JS files for CDN
-        shell: bash
+      - name: Install JS dependencies
         run: |
+          npm install --loglevel=error -g pug-cli less less-plugin-clean-css uglify-js
+          (cd js && npm ci --loglevel=error)
 
-          # Update version for the release branch
-          v=$(echo ${{ github.ref }} | cut -d / -f 4)
-          sed -i "s|public \$version.*|public \$version = '$v.0';|" src/App.php
-          npm install -g less-plugin-clean-css
-          (cd js; npm ci; npm run build; cd ..)
+      - name: Compile JS and CSS files for CDN
+        run: |
+          (cd js && npm run build)
+          sed -i "s~'https://raw.githack.com/atk4/ui/develop/public.*~'/public',~" src/App.php
+          
           lessc public/agileui.less public/agileui.css --clean-css="--s1 --advanced" --source-map
-          echo '!agileui.css.map' >> public/.gitignore
-          git add public
-          git config --global user.email "bundler@agiletoolkit.org"
-          git config --global user.name "Release Bundler"
-          git commit -am "Releasing $v.0"
-          echo "If everything is good and CI/CD pass - please manually create tag $v.0 on this commit ^^"
-
+          echo '!/agileui.css.map' >> public/.gitignore
 
       - name: Commit
         run: |
           git config --global user.name "$(git show -s --format='%an')"
           git config --global user.email "$(git show -s --format='%ae')"
-          git add -A && git diff --staged && git commit -m "Build Release"
+          git add -A && git diff --staged && git commit -m "Build Release \"${{ steps.target.outputs.version_name }}\""
 
       - name: Push
         uses: ad-m/github-push-action@master
